
---

## Intégrer ces fichiers dans la pipeline GitHub Actions

```yaml
# .github/workflows/deploy.yml (extrait)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Installe Python et dépendances
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt