name: Deploy portfolio to EC2

# ──────────────── Déclencheurs ────────────────
on:
  push:
    branches: [ main ]        # à chaque push sur la branche main
  workflow_dispatch:          # ou déclenchement manuel via GitHub

# ──────────────── Variables globales ────────────────
env:
  REGION: eu-north-1
  BUCKET: lancelot-bucket99
  ZIP_NAME: site.zip

# ──────────────── Tâche unique ────────────────
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Récupère le code source du dépôt
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Crée une archive ZIP avec les dossiers nécessaires
    - name: Zip site, content, scripts
      run: zip -r ${{ env.ZIP_NAME }} site content scripts

    # 3. Configure les identifiants AWS (venant des Secrets du dépôt)
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region:            ${{ env.REGION }}

    # 4. Supprime le ZIP précédent pour forcer l’événement S3
    - name: Delete existing ZIP
      run: aws s3 rm s3://${{ env.BUCKET }}/${{ env.ZIP_NAME }}

    # 5. Upload le ZIP dans S3 (déclenche Lambda)
    - name: Upload ZIP to S3
      run: aws s3 cp ${{ env.ZIP_NAME }} s3://${{ env.BUCKET }}/${{ env.ZIP_NAME }}
