name: Deploy portfolio to EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGION: eu-north-1
  BUCKET: lancelot-bucket99
  ZIP_NAME: site.zip
  LAMBDA_NAME: DeployPortfolioToEC2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip site, content, scripts
        run: zip -r ${{ env.ZIP_NAME }} site content scripts

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.REGION }}

      - name: Upload ZIP to S3
        run: aws s3 cp ${{ env.ZIP_NAME }} s3://${{ env.BUCKET }}/${{ env.ZIP_NAME }}

      - name: Invoke Lambda (sync)
        id: invoke_lambda
        run: |
          aws lambda invoke \
            --function-name ${{ env.LAMBDA_NAME }} \
            --payload '{}' \
            --invocation-type RequestResponse \
            --region ${{ env.REGION }} \
            response.json > /dev/null

          cat response.json

          STATUS_CODE=$(jq -r '.statusCode' response.json)

          if [ "$STATUS_CODE" != "200" ]; then
            echo "Lambda function failed. Status: $STATUS_CODE"
            exit 1
          fi

      - name: Done
        run: echo "✅ Lambda function ran successfully."
